### ISSUE TITLE
Move to archive toolbelt

### ISSUE THREAD

**Issue by mlieberman85** [ossf/toolbelt#14]
There is a lack of interest from volunteers in the community, especially from governing board member companies. Without support this work doesn't have a path forward.

**Comment by SecurityCRob** [comment]
we can mark the effort as "archived", but the materials should still remain available for reference & use (use cases, threats, etc).  That is all still value artifacts others may leverage

**Comment by mlieberman85** [comment]
Agreed. I think the materials are valuable. I also think it's probably worth highlighting this back to relevant parties who see there is a need for unifying the work we're doing within OpenSSF to make it easy for folks to implement the right security practices.

The need is still there, but it's unclear what the path forward is without support or a different direction.

**Comment by afmarcum** [comment]
@hythloda @redenmartinez What criteria need to be met to process this request to archive this SIG (while retaining the work completed for future use and reference)?

Six of the last eight meetings have been cancelled and the other two meetings had only two attendees each. Last Slack message was over a month ago inquiring about a meeting being cancelled.

**Comment by hythloda** [comment]
> @hythloda @redenmartinez What criteria need to be met to process this request to archive this SIG (while retaining the work completed for future use and reference)?
> 
> Six of the last eight meetings have been cancelled and the other two meetings had only two attendees each. Last Slack message was over a month ago inquiring about a meeting being cancelled.

From the [process doc ](https://github.com/ossf/tac/blob/main/process/templates/SIG_NAME_archived_stage.md) all elements have been achieved at it should be archived. No one from PMO has the ability to switch a repo to the archived status and any such change has to go through @bbpursell1

**Comment by sevansdell** [comment]
@jkjell / @mlieberman85 / @SecurityCRob / @bbpursell1 

Bennett, what do you need from co chairs above to archive the repo status but keep the materials available (per Crob's previous message above)?  It would be great if we could close this Issue.

**Comment by lehors** [comment]
@sevansdell Archiving a repo merely makes it read-only. All of its content remains accessible. And its easily reversible any time.

**Comment by bbpursell1** [comment]
> @jkjell / @mlieberman85 / @SecurityCRob / @bbpursell1
> 
> Bennett, what do you need from co chairs above to archive the repo status but keep the materials available (per Crob's previous message above)? It would be great if we could close this Issue.

@sevansdell The admins for the repository have the ability to and ideally should be the ones to archive the repository.  For this repo that would be these teams:  https://github.com/orgs/ossf/teams/admin-toolbelt and https://github.com/orgs/ossf/teams/admin-wg-best-practices, which have one member: @SecurityCRob.  But as the overall org owners, I can go ahead and do this, as could @Danajoyluck or @omkhar.

I can go ahead and archive the repository, but it may be good to close any open issues or pull requests, first.

**Comment by sevansdell** [comment]
@mlieberman85 , @jkjell , @SecurityCRob Please close out any open issues/PRS, then ping Bennett for help finalizing the archive. Thanks!

**Comment by jkjell** [comment]
Everything has been closed except this issue. Please archive the repo.

**Comment by riaankleinhans** [comment]
Closing this for archiving
